import Head from 'next/head';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';

import Spinner from 'components/Spinner';

export default function Home() {
  const { data: session, status } = useSession();
  const router = useRouter();

  if (status === 'loading') {
    return <Spinner />;
  }

  if (session) {
    router.push('/home');
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <a href='/api/auth/signin'>login</a>
      </main>
    </div>
  );
}
