import Head from 'next/head';
import Link from 'next/link';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';

import Spinner from 'components/Spinner';
import prisma from 'lib/prisma';
import { getTweets } from 'lib/data';
import Tweets from 'components/Tweets';

export const getServerSideProps = async () => {
  const take = 3;
  let tweets = await getTweets(prisma, take);
  tweets = JSON.parse(JSON.stringify(tweets));

  return {
    props: {
      tweets,
    },
  };
};

export default function Home({ tweets }) {
  const { data: session, status } = useSession();
  const router = useRouter();

  if (status === 'loading') {
    return <Spinner />;
  }

  if (session) {
    router.push('/home');
  }

  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='mt-10'>
        <div className='text-center p-4 border m-4'>
          <h2 className='mb-10'>Join the conversation!</h2>
          <Link href='/api/auth/signin'>
            <a className='border px-8 py-2 mt-5 font-bold rounded-full color-accent-contrast bg-color-accent hover:bg-color-accent-hover-darker'>
              login
            </a>
          </Link>
        </div>
        <Tweets tweets={tweets} />
      </div>
    </>
  );
}
